services:
  - type: web
    name: ss-status-tracker
    runtime: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DIGIFI_API_BASE_URL
        value: https://api.digifi.io/v1
      - key: DIGIFI_API_KEY
        sync: false
      - key: DIGIFI_TRACKING_TOKEN_VAR
        value: tracking_token
      - key: CLIENT_URL
        value: https://status.mysecondstreet.com
